In [2]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.23407048, -0.59532387, -0.49612312],
       [-0.40673706, -1.26432558, -0.63193747]])

In [3]:
data*10

array([[  2.34070475,  -5.95323868,  -4.96123122],
       [ -4.0673706 , -12.64325585,  -6.31937466]])

In [4]:
data+data

array([[ 0.46814095, -1.19064774, -0.99224624],
       [-0.81347412, -2.52865117, -1.26387493]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
data1 = [1,2,3,4,5,6,7]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
data2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2.shape

(3, 3)

In [14]:
np.add(arr1,arr1)

array([ 2,  4,  6,  8, 10, 12, 14])

In [15]:
np.diag(arr2)

array([1, 5, 9])

In [16]:
np.dot(arr2,arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])